### PR TITLE
Fixed appSize & appPos behavior

### PR DESCRIPTION
**Pull request by Halen84**
Fixed weird behavior with appStartupSize and appStartupPos

### CODE REVIEW

**Review by Halen84 — COMMENTED** [review]
Whoops! I didn't mean to revert "Update README.md"! Fixed it.

**Comment by Dealman** [comment]
Consider moving RefreshMercenaries() to be encompassed within _"Auto-find Game.ini + Set Default Backup Folder"_.

Trying to get the mercenaries without a path potentially being set could lead to issues, so having it refresh after it has successfully loaded the previous set path or upon setting the path would be a bit safer. 😄

**Comment by Halen84** [comment]
> Consider moving RefreshMercenaries() to be encompassed within _"Auto-find Game.ini + Set Default Backup Folder"_.
> 
> Trying to get the mercenaries without a path potentially being set could lead to issues, so having it refresh after it has successfully loaded the previous set path or upon setting the path would be a bit safer. 😄

Thank you for your input! I've edited the file and added a new check on RefreshMercenaries().

**Comment by Dealman** [comment]
Sorry for the delay, very nice - will go ahead and merge this - thanks a lot for the help! 💯

**Pull request merged**
